/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by virtual-next-routes@0.0.25
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// prettier-ignore
import { index, layout, rootRoute, route } from "@tanstack/virtual-file-routes";

// prettier-ignore
export const routes = rootRoute("layout.tsx", [
  layout("(dashboard)/layout.tsx", [
    route("x", [
      index("(dashboard)/x/page.tsx")
    ])
  ]),
  index("page.tsx")
]);
